- name:  variable in ansible
  hosts: mongodb
  vars:
   COURSE: Devops
   TRAINER: arun
   DURAION: 3mths
  tasks:
  - name: print helloworld
     ansible.builtin.debug:
      msg: "hello world"
  - name: print in varaibles
     ansible.builtin.debug:
      msg: "helloworld {{COURSE}}, trainer is {{TRAINER}}, duration is {{DURATION}}"